### ISSUE TITLE
Suggest does not work -- Missing nokogiri

### ISSUE THREAD

**Issue by ericboehs** [zhaocai/alfred2-google-workflow#1]
Nokogiri needs to be added to the Gemfile for the `g` shortcut to work. I got it working using my version of ruby 1.9.3 but I could never get nokogiri to build for ML's bundled 1.8.7. I tried doing this as well: http://stackoverflow.com/a/10912948

Also on line 44 there's a reference to "result" which doesn't exist in this context. Simply removing the line fixed it. I'll submit a PR for that.

**Comment by zhaocai** [comment]
Thanks. I have fixed the dependency to nokigiri. Now it should work with system ruby
